-- ============================================================
-- Migration 008: Storage Buckets + Storage RLS Policies
-- 3 private buckets. All files accessed via signed URLs only.
-- Never public. Signed URL expires in 1 hour (generated by backend).
-- Folder structure: {bucket}/{patient_id}/{filename}
-- RLS: users can only access files for their own patients.
-- ============================================================

-- ── Create Buckets ────────────────────────────────────────────

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  (
    'source-documents',
    'source-documents',
    false,
    52428800,
    ARRAY['image/jpeg','image/png','application/pdf','audio/mpeg','audio/ogg','audio/mp4','audio/wav']
  ),
  (
    'crisis-packet-pdfs',
    'crisis-packet-pdfs',
    false,
    5242880,
    ARRAY['application/pdf']
  ),
  (
    'medication-list-pdfs',
    'medication-list-pdfs',
    false,
    5242880,
    ARRAY['application/pdf']
  )
ON CONFLICT (id) DO NOTHING;


-- ── Storage RLS Policies ─────────────────────────────────────

-- source-documents: upload
CREATE POLICY "source_documents_upload" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'source-documents'
    AND (storage.foldername(name))[1]::uuid IN (SELECT public.get_user_patient_ids())
  );

-- source-documents: read
CREATE POLICY "source_documents_read" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'source-documents'
    AND (storage.foldername(name))[1]::uuid IN (SELECT public.get_user_patient_ids())
  );

-- crisis-packet-pdfs: read
CREATE POLICY "crisis_pdfs_read" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'crisis-packet-pdfs'
    AND (storage.foldername(name))[1]::uuid IN (SELECT public.get_user_patient_ids())
  );

-- medication-list-pdfs: read
CREATE POLICY "medication_pdfs_read" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'medication-list-pdfs'
    AND (storage.foldername(name))[1]::uuid IN (SELECT public.get_user_patient_ids())
  );

-- service_role can write to all buckets (backend PDF generation)
-- No policy needed — service_role bypasses RLS by default.
